language: cpp
compiler:
- gcc
os:
- linux
before_install:
- cd ./wxwidget/wxWidgets-2.8.12src/wxWidgets-2.8.12/
- mkdir buildgtk
- cd buildgtk
- ../configure --with-gtk
- make

branches:
  only:
  - master